### ISSUE TITLE
New Update for install doesn't work

### ISSUE THREAD

**Issue by dweebdog** [SBBTracker/SBBTracker#51]
Downloaded SBB tracker about 1 month ago, the update button/banner feature has never worked (I click on Yes and nothing happens, if I click remind me later the banner disappears). Several small bugs still exist like wrong cards display in people's comps on the tracker (which I assume have since been fixed)
I am wary of trying a fresh install and losing all my match history - but if there is a way to save this I am happy to reinstall SBBtracker

![image](https://user-images.githubusercontent.com/100752843/156309159-49bd9a4f-d544-4474-b00d-d9ab5f7933d6.png)

**Comment by andrewrasch** [comment]
There was an update that was released about a month ago that unfortunately broke the auto-updater. If you download the latest update from the releases page, run it and install over your existing tracker everything will be 100% fine. Your match history is stored separately from the installed files.

**Comment by JesterJensen** [comment]
Hey I imported all my data from the last possible date mid december and everything was fine. Since the update yesterday my tracker are chosing wrong heroes - so I delted all my data and reimported it on new, and now it says I have played 48 games with grandmother and many games with other sub heroes, so I guess the numbers or something have switched around - is there any way this can be solved?

**Comment by JesterJensen** [comment]
Yes was not sure if I should seperate it - so I will just answer once :) I have some back ups so I guess its better than none at all or just plain wrong data - just have to live with some missing data then-  thanks for the hint of getting the back up in line. Well I can for sure not help you in that matter, but I guess something with a timestamp/date could resolve the data from the version shifts.
